name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Cache Poetry cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache
        restore-keys: |
          poetry-cache
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install poetry
      run: pip install poetry
    - name: Install project dependencies
      run: poetry install
    - name: Check dependencies
      run: poetry run check-depz